services:
  # New MongoDB service
  # mongo:
  #   image: mongo:8.0.5
  #   container_name: mongo
  #   ports:
  #     - "${HOST_BACKEND_PORT}:{CONTAINER_BACKEND_PORT}"
  #   environment:
  #     # MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
  #     # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
  #     MONGO_INITDB_DATABASE: ${DB_NAME} # This can create the DB on init
  #   volumes:
  #     - mongo_data:/data/db # Default data directory for MongoDB

  backend:
    build: ./backend
    ports:
      # Uncomment the next line when using Docker
      # - "${HOST_BACKEND_PORT}:{CONTAINER_BACKEND_PORT}"
      # Comment the next three lines when using Docker
      - target: ${CONTAINER_BACKEND_PORT}
        published: ${HOST_BACKEND_PORT}
        protocol: tcp
    env_file:
      - ./backend/.env  # Loads app-specific variables for the backend
    # Uncomment the next line when using new MongoDB service
    # depends_on:
    #   - mongo
    volumes:
      # - ./backend:/usr/src/app
      []
    networks:
      - matbuddy_network

  frontend:
    build: ./frontend
    ports:
      # Uncomment the next line when using Docker
      # - "${HOST_FRONTEND_PORT}:${CONTAINER_FRONTEND_PORT}"
      # Comment the next three lines when using Docker
      - target: ${CONTAINER_FRONTEND_PORT}
        published: ${HOST_FRONTEND_PORT}
        protocol: tcp
      
    env_file:
      - ./frontend/.env  # Loads app-specific variables for the frontend
    depends_on:
      - backend
    volumes:
      # - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - matbuddy_network

# use this if you want to use a new MongoDB service
# Volumes are not defined here if MongoDB is fully external
# and its data persistence is managed elsewhere.
# volumes:
#   mongo_data:

networks:
  # Uncomment to define a new network for your app services
  # app-network:  # Define a new network for your app services
  #   driver: bridge # Standard bridge network

  # If using an existing network where MongoDB resides:
  # existing_mongo_network_name: # Replace with a friendly name for this compose file
  #   external: true
  #   name: actual_name_of_network_mongo_is_on # Get this from Portainer/docker inspect

  matbuddy_network:
    external: true
    name: app-network # This is the ACTUAL name of the Docker network on your Docker host.
                      # This network MUST exist before deploying the stack.
                      # Your existing Portainer-managed MongoDB container MUST be connected to this 'app-network'.