version: '3.8'

services:
  db:
    image: mongo:8.0.5
    ports:
      - "${HOST_MONGO_PORT}:27017"
    environment:
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${DB_NAME} # This can create the DB on init
    volumes:
      - mongo_data:/data/db # Default data directory for MongoDB

  backend:
    build: ./backend
    ports:
      - "${HOST_BACKEND_PORT}:8080"
    env_file:
      - ./backend/.env # Loads environment variables from backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build: ./frontend
    ports:
      - "${HOST_FRONTEND_PORT}:3000"
    env_file:
      - ./frontend/.env # Loads environment variables from frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo_data: