"""Initial version

Revision ID: 97902165922a
Revises: 
Create Date: 2025-03-19 05:58:11.649492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97902165922a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guidance_factor', sa.Float(), nullable=False),
    sa.Column('magnetic_density', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lattices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('no_of_atoms', sa.Integer(), nullable=False),
    sa.Column('cell_parameters', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=False),
    sa.Column('pbc', sa.String(), nullable=False),
    sa.Column('atoms_list', sa.JSON(), nullable=False),
    sa.Column('atoms', sa.JSON(), nullable=False),
    sa.Column('dft_predicted_energy', sa.Float(), nullable=True),
    sa.Column('dft_predicted_magnetic_property', sa.Float(), nullable=True),
    sa.Column('mattersim_predicted_energy', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lattices')
    op.drop_table('batches')
    # ### end Alembic commands ###
