hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,outputs/singlerun/${now:%Y-%m-%d}/${now:%H-%M-%S}}

auto_resume: True

defaults:
  - data_module: mp_20
  - trainer: default
  - lightning_module: default
  - lightning_module/diffusion_module: default
  - lightning_module/diffusion_module/model: mattergen
  - lightning_module/diffusion_module/corruption: default
